### ISSUE TITLE
Using for multiple values doesn't seem to work.

### ISSUE THREAD

**Issue by 412andrewmortimer** [OakMX/postcss-remify#2]
`background-size: rem(1143) rem(838);`

-- ends up looking like this in the css

`background-size: 71.4375rem;`

--same with doing things like padding

`padding: rem(5) rem(6) rem(7) rem(8);`

**Comment by 412andrewmortimer** [comment]
Also appears to be buggy with 
`border: rem(3) solid #ffffff;`

So, multi-argument-declarations.

**Comment by 412andrewmortimer** [comment]
Also negative integers may not work.

`top: rem(-114);`

**Comment by EduardoRT** [comment]
Thanks @412andrewmortimer, @JulsWlf is looking into this.

**Comment by 412andrewmortimer** [comment]
Thank you both. I appreciate the code. @EduardoRT @JulsWlf
